version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: furia_postgres
    restart: always
    environment:
      POSTGRES_USER: furia
      POSTGRES_PASSWORD: furia123
      POSTGRES_DB: furia_fan_intelligence
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: furia_rabbitmq
    restart: always
    ports:
      - "5672:5672"   # Porta para aplicações (ex: Bot)
      - "15672:15672" # Porta do painel web de administração
    environment:
      RABBITMQ_DEFAULT_USER: furia
      RABBITMQ_DEFAULT_PASS: furia123

volumes:
  postgres_data:
