"""

Revision ID: 248f8df872fd
Revises: 
Create Date: 2025-05-04 17:08:49.504666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '248f8df872fd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Fan',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('whatsapp_number', sa.String(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('cidade', sa.String(), nullable=False),
    sa.Column('cpf', sa.String(), nullable=True),
    sa.Column('optin_jogos', sa.String(), nullable=False),
    sa.Column('optin_promocoes', sa.String(), nullable=False),
    sa.Column('criado_em', sa.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('whatsapp_number')
    )
    op.create_table('KPIReport',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('data', sa.DateTime(), nullable=False),
    sa.Column('total_fans', sa.Integer(), nullable=False),
    sa.Column('opt_in_jogos', sa.Float(), nullable=False),
    sa.Column('opt_in_promo', sa.Float(), nullable=False),
    sa.Column('engajamento', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_KPIReport_id'), 'KPIReport', ['id'], unique=False)
    op.create_table('FanSegment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fan_id', sa.UUID(), nullable=False),
    sa.Column('cluster', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['fan_id'], ['Fan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_FanSegment_id'), 'FanSegment', ['id'], unique=False)
    op.create_table('Interaction',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('fan_id', sa.UUID(), nullable=False),
    sa.Column('question', sa.String(), nullable=False),
    sa.Column('answer', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['fan_id'], ['Fan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Notification',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('fan_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['fan_id'], ['Fan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Notification_id'), 'Notification', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Notification_id'), table_name='Notification')
    op.drop_table('Notification')
    op.drop_table('Interaction')
    op.drop_index(op.f('ix_FanSegment_id'), table_name='FanSegment')
    op.drop_table('FanSegment')
    op.drop_index(op.f('ix_KPIReport_id'), table_name='KPIReport')
    op.drop_table('KPIReport')
    op.drop_table('Fan')
    # ### end Alembic commands ###
