"""

Revision ID: 2c48f8609b38
Revises: 
Create Date: 2025-05-04 18:37:53.215781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c48f8609b38'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fan',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('whatsapp_number', sa.String(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('cidade', sa.String(), nullable=False),
    sa.Column('cpf', sa.String(), nullable=True),
    sa.Column('optin_jogos', sa.String(), nullable=False),
    sa.Column('optin_promocoes', sa.String(), nullable=False),
    sa.Column('criado_em', sa.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('whatsapp_number')
    )
    op.create_table('kpi_report',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('data', sa.DateTime(), nullable=False),
    sa.Column('total_fans', sa.Integer(), nullable=False),
    sa.Column('opt_in_jogos', sa.Float(), nullable=False),
    sa.Column('opt_in_promo', sa.Float(), nullable=False),
    sa.Column('engajamento', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kpi_report_id'), 'kpi_report', ['id'], unique=False)
    op.create_table('fan_segment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fan_id', sa.UUID(), nullable=False),
    sa.Column('cluster', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['fan_id'], ['fan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fan_segment_id'), 'fan_segment', ['id'], unique=False)
    op.create_table('interaction',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('fan_id', sa.UUID(), nullable=False),
    sa.Column('question', sa.String(), nullable=False),
    sa.Column('answer', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['fan_id'], ['fan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notification',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('fan_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['fan_id'], ['fan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_id'), 'notification', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notification_id'), table_name='notification')
    op.drop_table('notification')
    op.drop_table('interaction')
    op.drop_index(op.f('ix_fan_segment_id'), table_name='fan_segment')
    op.drop_table('fan_segment')
    op.drop_index(op.f('ix_kpi_report_id'), table_name='kpi_report')
    op.drop_table('kpi_report')
    op.drop_table('fan')
    # ### end Alembic commands ###
